{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-backend
spec:
  hosts:
    {{- range .Values.istio.virtualService.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    {{- range .Values.istio.virtualService.gateways }}
    - {{ $.Release.Name }}-{{ . }}
    {{- end }}
  http:
    - route:
      - destination:
          host: {{ .Release.Name }}-backend
          port:
            number: {{ .Values.service.port }}
{{- end }} 