apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
    app: {{ .Release.Name }}-backend
type: Opaque
data:
  {{- range $key, $val := .Values.environment.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }} 